version: "3"
services:
  mysql-dev:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "gaandeweg-dev"
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
  
  postgresql-dev:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "gaandeweg-dev"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always